import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';
import type { Plugin } from 'vite';

type Asset = { url: string; sha256: string };

async function listFiles(root: string, dir = root): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name);
      return entry.isDirectory() ? listFiles(root, path) : [path];
    }),
  );
  return nested.flat();
}

/** Generate a versioned, verified precache from every file in a Vite production build. */
export function pwacnOffline(options: { swFile?: string } = {}): Plugin {
  let outDir = '';
  let base = '/';
  const swFile = options.swFile ?? 'sw.js';
  return {
    name: 'pwacn-offline',
    apply: 'build',
    configResolved(config) {
      outDir = resolve(config.root, config.build.outDir);
      base = config.base;
      if (!base.startsWith('/') || !base.endsWith('/'))
        throw new Error('pwacnOffline requires an absolute path Vite base ending in /');
    },
    async closeBundle() {
      const files = (await listFiles(outDir)).filter(
        (file) =>
          !['offline-assets.json', 'vercel.json', swFile].includes(
            relative(outDir, file),
          ),
      );
      const assets: Asset[] = await Promise.all(
        files.map(async (file) => ({
          url: base + relative(outDir, file).split(sep).map(encodeURIComponent).join('/'),
          sha256: createHash('sha256')
            .update(await readFile(file))
            .digest('hex'),
        })),
      );
      assets.sort((a, b) => a.url.localeCompare(b.url));
      const buildId = createHash('sha256')
        .update(JSON.stringify(assets))
        .digest('hex')
        .slice(0, 16);
      const manifest = { buildId, assets };
      await writeFile(
        join(outDir, 'offline-assets.json'),
        `${JSON.stringify(manifest, null, 2)}\n`,
      );
      await writeFile(join(outDir, swFile), serviceWorkerSource(manifest, base));
    },
  };
}

function serviceWorkerSource(
  manifest: { buildId: string; assets: Asset[] },
  base: string,
): string {
  return (
    `// Generated by @pwacn/offline. Do not edit.\n` +
    `const BUILD = ${JSON.stringify(manifest.buildId)};\n` +
    `const ASSETS = ${JSON.stringify(manifest.assets)};\n` +
    `const BASE = ${JSON.stringify(base)};\n` +
    `const PREFIX = 'pwacn-static-';\n` +
    `const CACHE = PREFIX + BUILD;\n` +
    `const REQUIRED = new Map(ASSETS.map(asset => [new URL(asset.url, self.location.origin).pathname, asset]));\n` +
    `async function valid(response, expected) {
  if (!response || !response.ok || response.type === 'opaque') return false;
  const bytes = await response.clone().arrayBuffer();
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  const actual = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
  return actual === expected;
}
async function download(cache, asset) {
  const response = await fetch(asset.url, { cache: 'reload' });
  if (!await valid(response, asset.sha256)) throw new Error('Offline asset failed verification: ' + asset.url);
  await cache.put(asset.url, response);
}
async function missing(cache) {
  const absent = [];
  for (const asset of ASSETS) if (!await cache.match(asset.url)) absent.push(asset);
  return absent;
}
async function restore() {
  const cache = await caches.open(CACHE);
  const absent = await missing(cache);
  if (absent.length) await Promise.all(absent.map(asset => download(cache, asset)));
  return (await missing(cache)).length === 0;
}
async function announce(ready) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const client of clients) client.postMessage({ type: 'pwacn:offline', ready, buildId: BUILD });
}
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    try {
      if (!await restore()) throw new Error('Incomplete offline cache');
      await self.skipWaiting();
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    // Preserve the previous complete build for clients still running its chunks.
    const keys = (await caches.keys()).filter(key => key.startsWith(PREFIX));
    const previous = keys.filter(key => key !== CACHE).at(-1);
    await Promise.all(keys.filter(key => key !== CACHE && key !== previous).map(key => caches.delete(key)));
    await self.clients.claim();
    await announce(await restore().catch(() => false));
  })());
});
self.addEventListener('message', event => {
  if (event.data?.type !== 'pwacn:offline-status') return;
  event.waitUntil((async () => {
    const ready = await restore().catch(() => false);
    event.source?.postMessage({ type: 'pwacn:offline', ready, buildId: BUILD });
  })());
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE)) return;
  const path = event.request.mode === 'navigate' ? BASE + 'index.html' : url.pathname;
  const asset = REQUIRED.get(path);
  if (!asset) {
    // An older open client may still import a chunk from the previous complete build.
    event.respondWith((async () => {
      const keys = (await caches.keys()).filter(key => key.startsWith(PREFIX) && key !== CACHE);
      const previous = keys.at(-1);
      const cached = previous ? await (await caches.open(previous)).match(event.request) : undefined;
      return cached || fetch(event.request);
    })());
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(asset.url);
    if (cached) return cached;
    try {
      await download(cache, asset);
      void announce((await missing(cache)).length === 0);
      return (await cache.match(asset.url));
    } catch {
      void announce(false);
      // A missing JS or CSS asset must never receive HTML.
      if (event.request.mode === 'navigate') return new Response('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offline copy unavailable</title><main style="font:16px system-ui;padding:2rem"><h1>Offline copy unavailable</h1><p>Reconnect to download and verify this app, then try again.</p><button onclick="location.reload()">Try again</button></main>', { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
      return new Response('Required offline asset unavailable', { status: 503, headers: { 'Content-Type': 'text/plain' } });
    }
  })());
});\n`
  );
}
